name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          rsync -av --delete ./ /home/ubuntu/dvps/
          cd /home/ubuntu/dvps
          npm i
          npm run test
          pm2 restart nodeapp
